services:
  db:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: fit-ai-api
      POSTGRES_PASSWORD: fit-ai-api
      POSTGRES_DB: fit-ai-db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
